import type { DesignSystemMeta, DesignSystemType, ComponentsConfig, AppConfig, ImageAssetConfig } from '@/types/config'

export const DEFAULT_IMAGE_ASSET: ImageAssetConfig = {
  assetType: 'app-icon',
  themeMotif: '洗練されたミニマルなアプリアイコンシンボル',
  targetAi: 'gemini',
  aspectRatio: '1:1',
  includeNegativePrompt: true,
}

export const DEFAULT_COMPONENTS: ComponentsConfig = {
  titlebar: false,
  sidebar: true,
  navbar: false,
  profileArea: true,
  contextHeader: true,
  heroSection: false,
  bentoContainer: true,
  statCards: true,
  charts: true,
  activityTable: true,
  minimalForm: true,
  actionButtons: true,
  statusBar: true,
}

export const DESIGN_SYSTEMS: Record<DesignSystemType, DesignSystemMeta> = {
  bento: {
    id: 'bento',
    name: 'Bento Grid / モジュラー',
    subtitle: '2025-2026年 最も主流なモジュラータイルレイアウト',
    description: '情報を美しく整然とした角丸タイル状に分割し、視線誘導と情報密度を両立する万能スタイル。',
    defaultRules: {
      gap: 20,
      padding: 24,
      borderRadius: 16,
      borderWidth: 1,
      buttonGap: 10,
      h1Size: '3.5rem',
      h1Weight: 800,
      bodySize: '1rem',
      maxWidth: '1280px',
    },
    defaultColors: {
      base: '#0a0a0c',
      surface: '#16161a',
      primaryText: '#f4f4f6',
      secondaryText: '#82828c',
      accent: '#38bdf8',
      border: '#2a2a32',
    },
    defaultLightColors: {
      base: '#f8fafc',
      surface: '#ffffff',
      primaryText: '#0f172a',
      secondaryText: '#64748b',
      accent: '#0284c7',
      border: '#e2e8f0',
    },
  },
  brutalism: {
    id: 'brutalism',
    name: 'タクタイル・ブルータリズム',
    subtitle: 'ぼかし影なし・1-2pxソリッド線・硬質な幾何学構造',
    description: 'エンジニアライクな機能美と構築精度を表現する、角丸0pxと高コントラスト境界線のエッジスタイル。',
    defaultRules: {
      gap: 24,
      padding: 24,
      borderRadius: 0,
      borderWidth: 2,
      buttonGap: 12,
      h1Size: '3.25rem',
      h1Weight: 900,
      bodySize: '1rem',
      maxWidth: '1440px',
    },
    defaultColors: {
      base: '#0d0e12',
      surface: '#181920',
      primaryText: '#ffffff',
      secondaryText: '#9ca3af',
      accent: '#ff5a1f',
      border: '#ffffff',
    },
    defaultLightColors: {
      base: '#fef08a',
      surface: '#ffffff',
      primaryText: '#000000',
      secondaryText: '#1f2937',
      accent: '#e11d48',
      border: '#000000',
    },
  },
  minimal: {
    id: 'minimal',
    name: 'ミニマリズム UI',
    subtitle: '余計な装飾を削ぎ落とし、広大な余白とタイポグラフィに集中',
    description: 'タスクとコンテンツの可読性を極限まで高め、思考ノイズをゼロにするAIネイティブなシンプルスタイル。',
    defaultRules: {
      gap: 28,
      padding: 28,
      borderRadius: 8,
      borderWidth: 1,
      buttonGap: 12,
      h1Size: '3rem',
      h1Weight: 700,
      bodySize: '1rem',
      maxWidth: '1200px',
    },
    defaultColors: {
      base: '#09090b',
      surface: '#121216',
      primaryText: '#f8fafc',
      secondaryText: '#71717a',
      accent: '#6366f1',
      border: '#27272a',
    },
    defaultLightColors: {
      base: '#ffffff',
      surface: '#f8fafc',
      primaryText: '#09090b',
      secondaryText: '#71717a',
      accent: '#4f46e5',
      border: '#e4e4e7',
    },
  },
  retrofuturistic: {
    id: 'retrofuturistic',
    name: 'レトロフューチャリズム',
    subtitle: '90年代ノスタルジーとサイバーパンクの融合',
    description: 'ネオンの微細な光彩とダークマゼンタのトーンで、先進性と懐かしさを併せ持つ個性派スタイル。',
    defaultRules: {
      gap: 20,
      padding: 20,
      borderRadius: 4,
      borderWidth: 1,
      buttonGap: 8,
      h1Size: '3rem',
      h1Weight: 800,
      bodySize: '0.95rem',
      maxWidth: '1280px',
    },
    defaultColors: {
      base: '#070510',
      surface: '#130e24',
      primaryText: '#00f5d4',
      secondaryText: '#c084fc',
      accent: '#f43f5e',
      border: '#3c2368',
    },
    defaultLightColors: {
      base: '#f1f5f9',
      surface: '#ffffff',
      primaryText: '#0f172a',
      secondaryText: '#7c3aed',
      accent: '#ec4899',
      border: '#cbd5e1',
    },
  },
  glassmorphism: {
    id: 'glassmorphism',
    name: 'グラスモフィズム',
    subtitle: 'Apple Vision Pro以降洗練された、美しいすりガラス調レイヤー',
    description: '背景の透過ぼかし（backdrop blur）と繊細なホワイトボーダーにより、空間的な奥行きを演出するスタイル。',
    defaultRules: {
      gap: 24,
      padding: 24,
      borderRadius: 20,
      borderWidth: 1,
      buttonGap: 10,
      h1Size: '3.5rem',
      h1Weight: 700,
      bodySize: '1rem',
      maxWidth: '1280px',
    },
    defaultColors: {
      base: '#0a0e1a',
      surface: 'rgba(255, 255, 255, 0.06)',
      primaryText: '#ffffff',
      secondaryText: '#94a3b8',
      accent: '#38bdf8',
      border: 'rgba(255, 255, 255, 0.15)',
    },
    defaultLightColors: {
      base: '#e0e7ff',
      surface: 'rgba(255, 255, 255, 0.75)',
      primaryText: '#1e1b4b',
      secondaryText: '#4338ca',
      accent: '#3b82f6',
      border: 'rgba(255, 255, 255, 0.85)',
    },
  },
  kawaii: {
    id: 'kawaii',
    name: 'Kawaii / パステルポップ',
    subtitle: 'ぷっくり角丸・ソフトシャドウ・パステルカラーのキュートな世界観',
    description: '丸みを帯びたバブル感と柔らかな光の拡散、パステル調（ピンク・ミント・ラベンダー）でユーザーに愛着と安心感を与えるスタイル。',
    defaultRules: {
      gap: 20,
      padding: 24,
      borderRadius: 24,
      borderWidth: 1,
      buttonGap: 14,
      h1Size: '3.25rem',
      h1Weight: 800,
      bodySize: '1rem',
      maxWidth: '1280px',
    },
    defaultColors: {
      base: '#18131d',
      surface: '#251c2d',
      primaryText: '#fdf2f8',
      secondaryText: '#d8b4e2',
      accent: '#f472b6',
      border: '#3d2d49',
    },
    defaultLightColors: {
      base: '#fff5f7',
      surface: '#ffffff',
      primaryText: '#372535',
      secondaryText: '#86687f',
      accent: '#ec4899',
      border: '#fed7e2',
    },
  },
  gaming: {
    id: 'gaming',
    name: 'Webゲーム / アーケード・ピクセル',
    subtitle: '8bit/16bitレトロゲーム・サイバーネオン・HUDステータス',
    description: '直角のソリッドなドット枠、HP/MPゲージ風インジケーター、ネオングローが生み出すアーケードゲーム特有の高揚感。',
    defaultRules: {
      gap: 16,
      padding: 20,
      borderRadius: 2,
      borderWidth: 2,
      buttonGap: 12,
      h1Size: '3rem',
      h1Weight: 900,
      bodySize: '0.95rem',
      maxWidth: '1280px',
    },
    defaultColors: {
      base: '#090a10',
      surface: '#121524',
      primaryText: '#00ffcc',
      secondaryText: '#a855f7',
      accent: '#ff007f',
      border: '#00e5ff',
    },
    defaultLightColors: {
      base: '#f0fdf4',
      surface: '#ffffff',
      primaryText: '#052e16',
      secondaryText: '#15803d',
      accent: '#e11d48',
      border: '#16a34a',
    },
  },
}

export function createInitialConfig(): AppConfig {
  const bento = DESIGN_SYSTEMS.bento
  return {
    version: 1,
    platform: 'web',
    themeMode: 'dark',
    designSystem: 'bento',
    rules: { ...bento.defaultRules },
    colors: { ...bento.defaultColors },
    components: { ...DEFAULT_COMPONENTS },
    customPurpose: '',
    outputTechStack: 'react-tailwind',
    imageAsset: { ...DEFAULT_IMAGE_ASSET },
  }
}
